name: Update README & endpoints

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  styx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
    
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Compile
        run: |
          uv run update_readme.py

      - name: Git commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add packages/
          git add README.md
          git diff --quiet HEAD || git commit -m "Compile"
          git push
